/* ========================================================================
 * Copyright (c) 2005-2024 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Text;
using System.IO;
using Opc.Ua;


#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CA1515 // Consider making public types internal
#pragma warning disable CA1707 // Identifiers should not contain underscores
#pragma warning disable CA1028 // Enum Storage should be Int32

namespace Opc.Ua.WotCon
{
    #region _ClassName_ Declarations
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Opc.Ua.ModelCompiler", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public static partial class PredefinedNodes
    {
        #region PredefinedNodes Declarations
        // <summary/>
        public static NodeStateCollection Load(ISystemContext context)
        {
            byte[] initializationBuffer = Convert.FromBase64String(
               "AQAAACQAAABodHRwOi8vb3BjZm91bmRhdGlvbi5vcmcvVUEvV29ULUNvbi//////BwAAAARgwAoBAAAA" +
               "FwAAAFdvdENvbk5hbWVzcGFjZU1ldGFkYXRhAQAkAAAAaHR0cDovL29wY2ZvdW5kYXRpb24ub3JnL1VB" +
               "L1dvVC1Db24vAQFDAAAvAQBgLUMAAAABAAAAAC8BAQDDLQsAAAAVYKkKAgAAAAAADAAAAE5hbWVzcGFj" +
               "ZVVyaQEBRAAALgBERAAAAAwkAAAAaHR0cDovL29wY2ZvdW5kYXRpb24ub3JnL1VBL1dvVC1Db24vAAz/" +
               "////AQH/////AAAAABVgqQoCAAAAAAAQAAAATmFtZXNwYWNlVmVyc2lvbgEBRQAALgBERQAAAAwGAAAA" +
               "MS4wMi4wAAz/////AQH/////AAAAABVgqQoCAAAAAAAYAAAATmFtZXNwYWNlUHVibGljYXRpb25EYXRl" +
               "AQFGAAAuAERGAAAADQDAWRl6ZdwBAA3/////AQH/////AAAAABVgqQoCAAAAAAARAAAASXNOYW1lc3Bh" +
               "Y2VTdWJzZXQBAUcAAC4AREcAAAABAAAB/////wEB/////wAAAAAXYKkKAgAAAAAAEQAAAFN0YXRpY05v" +
               "ZGVJZFR5cGVzAQFIAAAuAERIAAAAhgEAAAAAAAAAAQAAAQEAAAABAAAAAAAAAAEB/////wAAAAAXYKkK" +
               "AgAAAAAAGAAAAFN0YXRpY051bWVyaWNOb2RlSWRSYW5nZQEBSQAALgBESQAAAIwBAAAADAAAADE6MjE0" +
               "NzQ4MzY0NwEAIwEBAAAAAQAAAAAAAAABAf////8AAAAAFWCpCgIAAAAAABkAAABTdGF0aWNTdHJpbmdO" +
               "b2RlSWRQYXR0ZXJuAQFKAAAuAERKAAAADAAAAAAADP////8BAf////8AAAAAF2CJCgIAAAAAABYAAABE" +
               "ZWZhdWx0Um9sZVBlcm1pc3Npb25zAQFjAAAuAERjAAAAAGABAAAAAQAAAAAAAAABAf////8AAAAAF2CJ" +
               "CgIAAAAAABoAAABEZWZhdWx0VXNlclJvbGVQZXJtaXNzaW9ucwEBZAAALgBEZAAAAABgAQAAAAEAAAAA" +
               "AAAAAQH/////AAAAABVgiQoCAAAAAAAZAAAARGVmYXVsdEFjY2Vzc1Jlc3RyaWN0aW9ucwEBZQAALgBE" +
               "ZQAAAABf/////wEB/////wAAAAAVYKkKAgAAAAAADAAAAE1vZGVsVmVyc2lvbgEBJwAALgBEJwAAAAwF" +
               "AAAAMS4yLjABAMde/////wEB/////wAAAAAEYAAQCAAAAAEAIAAAAFdvVEFzc2V0Q29ubmVjdGlvbk1h" +
               "bmFnZW1lbnRUeXBlAQEBAAA6/////wgAAAAEYMALAQAAABgAAABXb1RBc3NldE5hbWVfUGxhY2Vob2xk" +
               "ZXIBAA4AAAA8V29UQXNzZXROYW1lPgEBAgAAIwA6AQD0LAIAAAACAAAAAQDDRAABASoAAQGOAAABAUIA" +
               "AgAAAARggAsBAAAAAQAHAAAAV29URmlsZQEBkAAALwEBbgAATpAAAAD/////CwAAABVgiQsCAAAAAAAE" +
               "AAAAU2l6ZQEBkQAALgBEAE6RAAAAAAn/////AQH/////AAAAABVgiQsCAAAAAAAIAAAAV3JpdGFibGUB" +
               "AZIAAC4ARABOkgAAAAAB/////wEB/////wAAAAAVYIkLAgAAAAAADAAAAFVzZXJXcml0YWJsZQEBkwAA" +
               "LgBEAE6TAAAAAAH/////AQH/////AAAAABVgiQsCAAAAAAAJAAAAT3BlbkNvdW50AQGUAAAuAEQATpQA" +
               "AAAABf////8BAf////8AAAAABGGCCwQAAAAAAAQAAABPcGVuAQGYAAAvAQA8LQBOmAAAAAEB/////wIA" +
               "AAAXYKkLAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQGZAAAuAEQATpkAAACWAQAAAAEAKgEBEwAAAAQA" +
               "AABNb2RlAAP/////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAABdgqQsCAAAAAAAPAAAAT3V0" +
               "cHV0QXJndW1lbnRzAQGaAAAuAEQATpoAAACWAQAAAAEAKgEBGQAAAAoAAABGaWxlSGFuZGxlAAf/////" +
               "AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAAARhggsEAAAAAAAFAAAAQ2xvc2UBAZsAAC8BAD8t" +
               "AE6bAAAAAQH/////AQAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAZwAAC4ARABOnAAAAJYB" +
               "AAAAAQAqAQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8A" +
               "AAAABGGCCwQAAAAAAAQAAABSZWFkAQGdAAAvAQBBLQBOnQAAAAEB/////wIAAAAXYKkLAgAAAAAADgAA" +
               "AElucHV0QXJndW1lbnRzAQGeAAAuAEQATp4AAACWAgAAAAEAKgEBGQAAAAoAAABGaWxlSGFuZGxlAAf/" +
               "////AAAAAAABACoBARUAAAAGAAAATGVuZ3RoAAb/////AAAAAAABACgBAQAAAAEAAAACAAAAAQH/////" +
               "AAAAABdgqQsCAAAAAAAPAAAAT3V0cHV0QXJndW1lbnRzAQGfAAAuAEQATp8AAACWAQAAAAEAKgEBEwAA" +
               "AAQAAABEYXRhAA//////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAAARhggsEAAAAAAAFAAAA" +
               "V3JpdGUBAaAAAC8BAEQtAE6gAAAAAQH/////AQAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMB" +
               "AaEAAC4ARABOoQAAAJYCAAAAAQAqAQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEAKgEBEwAA" +
               "AAQAAABEYXRhAA//////AAAAAAABACgBAQAAAAEAAAACAAAAAQH/////AAAAAARhggsEAAAAAAALAAAA" +
               "R2V0UG9zaXRpb24BAaIAAC8BAEYtAE6iAAAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1" +
               "bWVudHMBAaMAAC4ARABOowAAAJYBAAAAAQAqAQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEA" +
               "KAEBAAAAAQAAAAEAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBAaQAAC4A" +
               "RABOpAAAAJYBAAAAAQAqAQEXAAAACAAAAFBvc2l0aW9uAAn/////AAAAAAABACgBAQAAAAEAAAABAAAA" +
               "AQH/////AAAAAARhggsEAAAAAAALAAAAU2V0UG9zaXRpb24BAaUAAC8BAEktAE6lAAAAAQH/////AQAA" +
               "ABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAaYAAC4ARABOpgAAAJYCAAAAAQAqAQEZAAAACgAA" +
               "AEZpbGVIYW5kbGUAB/////8AAAAAAAEAKgEBFwAAAAgAAABQb3NpdGlvbgAJ/////wAAAAAAAQAoAQEA" +
               "AAABAAAAAgAAAAEB/////wAAAAAEYYILBAAAAAEADgAAAENsb3NlQW5kVXBkYXRlAQGnAAAvAQFvAABO" +
               "pwAAAAEB/////wEAAAAXYKkLAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQGoAAAuAEQATqgAAACWAQAA" +
               "AAEAKgEBGQAAAAoAAABGaWxlSGFuZGxlAAf/////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAA" +
               "ABVgiQsCAAAAAQANAAAAQXNzZXRFbmRwb2ludAEBqQAALgBEAFCpAAAAAAz/////AQH/////AAAAABdg" +
               "iQsCAAAAAQAUAAAAU3VwcG9ydGVkV29UQmluZGluZ3MBASgAAC4ARABQKAAAAAEAx1wBAAAAAQAAAAAA" +
               "AAABAf////8AAAAABGGCCwQAAAABAAsAAABDcmVhdGVBc3NldAEBGgAALwEBGgAAThoAAAABAf////8C" +
               "AAAAF2CpCwIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBGwAALgBEAE4bAAAAlgEAAAABACoBARgAAAAJ" +
               "AAAAQXNzZXROYW1lAAz/////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAABdgqQsCAAAAAAAP" +
               "AAAAT3V0cHV0QXJndW1lbnRzAQEcAAAuAEQAThwAAACWAQAAAAEAKgEBFgAAAAcAAABBc3NldElkABH/" +
               "////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAAARhggsEAAAAAQALAAAARGVsZXRlQXNzZXQB" +
               "AR0AAC8BAR0AAE4dAAAAAQH/////AQAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAR4AAC4A" +
               "RABOHgAAAJYBAAAAAQAqAQEWAAAABwAAAEFzc2V0SWQAEf////8AAAAAAAEAKAEBAAAAAQAAAAEAAAAB" +
               "Af////8AAAAABGGCCwQAAAABAA4AAABEaXNjb3ZlckFzc2V0cwEBKQAALwEBKQAAUCkAAAABAf////8B" +
               "AAAAF2CpCwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBATAAAC4ARABOMAAAAJYBAAAAAQAqAQEhAAAA" +
               "DgAAAEFzc2V0RW5kcG9pbnRzAAwBAAAAAQAAAAAAAAAAAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAE" +
               "YYILBAAAAAEAFgAAAENyZWF0ZUFzc2V0Rm9yRW5kcG9pbnQBATEAAC8BATEAAFAxAAAAAQH/////AgAA" +
               "ABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBATIAAC4ARABOMgAAAJYCAAAAAQAqAQEYAAAACQAA" +
               "AEFzc2V0TmFtZQAM/////wAAAAAAAQAqAQEcAAAADQAAAEFzc2V0RW5kcG9pbnQADP////8AAAAAAAEA" +
               "KAEBAAAAAQAAAAIAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBAaoAAC4A" +
               "RABOqgAAAJYBAAAAAQAqAQEWAAAABwAAAEFzc2V0SWQAEf////8AAAAAAAEAKAEBAAAAAQAAAAEAAAAB" +
               "Af////8AAAAABGGCCwQAAAABAA4AAABDb25uZWN0aW9uVGVzdAEBSwAALwEBSwAAUEsAAAABAf////8C" +
               "AAAAF2CpCwIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBTAAALgBEAE5MAAAAlgEAAAABACoBARwAAAAN" +
               "AAAAQXNzZXRFbmRwb2ludAAM/////wAAAAAAAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAXYKkLAgAA" +
               "AAAADwAAAE91dHB1dEFyZ3VtZW50cwEBTQAALgBEAE5NAAAAlgIAAAABACoBARYAAAAHAAAAU3VjY2Vz" +
               "cwAB/////wAAAAAAAQAqAQEVAAAABgAAAFN0YXR1cwAM/////wAAAAAAAQAoAQEAAAABAAAAAgAAAAEB" +
               "/////wAAAAAEYIALAQAAAAEADQAAAENvbmZpZ3VyYXRpb24BAU4AAC8BAWkAAFBOAAAA/////wAAAAAE" +
               "YIAKAQAAAAEAHAAAAFdvVEFzc2V0Q29ubmVjdGlvbk1hbmFnZW1lbnQBAR8AAC8BAQEAHwAAAAEAAAAA" +
               "IwEAVQIAAAAEYYIKBAAAAAEACwAAAENyZWF0ZUFzc2V0AQEgAAAvAQEaACAAAAABAf////8CAAAAF2Cp" +
               "CgIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBIQAALgBEIQAAAJYBAAAAAQAqAQEYAAAACQAAAEFzc2V0" +
               "TmFtZQAM/////wAAAAAAAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAXYKkKAgAAAAAADwAAAE91dHB1" +
               "dEFyZ3VtZW50cwEBIgAALgBEIgAAAJYBAAAAAQAqAQEWAAAABwAAAEFzc2V0SWQAEf////8AAAAAAAEA" +
               "KAEBAAAAAQAAAAEAAAABAf////8AAAAABGGCCgQAAAABAAsAAABEZWxldGVBc3NldAEBIwAALwEBHQAj" +
               "AAAAAQH/////AQAAABdgqQoCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBASQAAC4ARCQAAACWAQAAAAEA" +
               "KgEBFgAAAAcAAABBc3NldElkABH/////AAAAAAABACgBAQAAAAEAAAABAAAAAQH/////AAAAAARgABAI" +
               "AAAAAQAZAAAAV29UQXNzZXRDb25maWd1cmF0aW9uVHlwZQEBaQABAMJE/////wIAAAAVYMkLAgAAACkA" +
               "AABXb1RDb25maWd1cmF0aW9uUGFyYW1ldGVyTmFtZV9QbGFjZWhvbGRlcgEAHwAAADxXb1RDb25maWd1" +
               "cmF0aW9uUGFyYW1ldGVyTmFtZT4BAWwAAC4ARAEA9CxsAAAAABj/////AQH/////AAAAABVgiQsCAAAA" +
               "AQAHAAAATGljZW5zZQEBbQAALgBEAFBtAAAAAAz/////AQH/////AAAAAARoABAIAAAAAQANAAAASVdv" +
               "VEFzc2V0VHlwZQEBKgABAMJEAf////8DAAAABGCACwEAAAABAAcAAABXb1RGaWxlAQErAAAvAQFuAABO" +
               "KwAAAP////8LAAAAFWCJCwIAAAAAAAQAAABTaXplAQEsAAAuAEQATiwAAAAACf////8BAf////8AAAAA" +
               "FWCJCwIAAAAAAAgAAABXcml0YWJsZQEBLQAALgBEAE4tAAAAAAH/////AQH/////AAAAABVgiQsCAAAA" +
               "AAAMAAAAVXNlcldyaXRhYmxlAQEuAAAuAEQATi4AAAAAAf////8BAf////8AAAAAFWCJCwIAAAAAAAkA" +
               "AABPcGVuQ291bnQBAS8AAC4ARABOLwAAAAAF/////wEB/////wAAAAAEYYILBAAAAAAABAAAAE9wZW4B" +
               "ATMAAC8BADwtAE4zAAAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBATQAAC4A" +
               "RABONAAAAJYBAAAAAQAqAQETAAAABAAAAE1vZGUAA/////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf//" +
               "//8AAAAAF2CpCwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBATUAAC4ARABONQAAAJYBAAAAAQAqAQEZ" +
               "AAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAABGGCCwQA" +
               "AAAAAAUAAABDbG9zZQEBNgAALwEAPy0ATjYAAAABAf////8BAAAAF2CpCwIAAAAAAA4AAABJbnB1dEFy" +
               "Z3VtZW50cwEBNwAALgBEAE43AAAAlgEAAAABACoBARkAAAAKAAAARmlsZUhhbmRsZQAH/////wAAAAAA" +
               "AQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAEYYILBAAAAAAABAAAAFJlYWQBATgAAC8BAEEtAE44AAAA" +
               "AQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBATkAAC4ARABOOQAAAJYCAAAAAQAq" +
               "AQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEAKgEBFQAAAAYAAABMZW5ndGgABv////8AAAAA" +
               "AAEAKAEBAAAAAQAAAAIAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBAToA" +
               "AC4ARABOOgAAAJYBAAAAAQAqAQETAAAABAAAAERhdGEAD/////8AAAAAAAEAKAEBAAAAAQAAAAEAAAAB" +
               "Af////8AAAAABGGCCwQAAAAAAAUAAABXcml0ZQEBOwAALwEARC0ATjsAAAABAf////8BAAAAF2CpCwIA" +
               "AAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBPAAALgBEAE48AAAAlgIAAAABACoBARkAAAAKAAAARmlsZUhh" +
               "bmRsZQAH/////wAAAAAAAQAqAQETAAAABAAAAERhdGEAD/////8AAAAAAAEAKAEBAAAAAQAAAAIAAAAB" +
               "Af////8AAAAABGGCCwQAAAAAAAsAAABHZXRQb3NpdGlvbgEBPQAALwEARi0ATj0AAAABAf////8CAAAA" +
               "F2CpCwIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBPgAALgBEAE4+AAAAlgEAAAABACoBARkAAAAKAAAA" +
               "RmlsZUhhbmRsZQAH/////wAAAAAAAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAXYKkLAgAAAAAADwAA" +
               "AE91dHB1dEFyZ3VtZW50cwEBPwAALgBEAE4/AAAAlgEAAAABACoBARcAAAAIAAAAUG9zaXRpb24ACf//" +
               "//8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAABGGCCwQAAAAAAAsAAABTZXRQb3NpdGlvbgEB" +
               "QAAALwEASS0ATkAAAAABAf////8BAAAAF2CpCwIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBQQAALgBE" +
               "AE5BAAAAlgIAAAABACoBARkAAAAKAAAARmlsZUhhbmRsZQAH/////wAAAAAAAQAqAQEXAAAACAAAAFBv" +
               "c2l0aW9uAAn/////AAAAAAABACgBAQAAAAEAAAACAAAAAQH/////AAAAAARhggsEAAAAAQAOAAAAQ2xv" +
               "c2VBbmRVcGRhdGUBAWoAAC8BAW8AAE5qAAAAAQH/////AQAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1" +
               "bWVudHMBAWsAAC4ARABOawAAAJYBAAAAAQAqAQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8AAAAAAAEA" +
               "KAEBAAAAAQAAAAEAAAABAf////8AAAAAFWCJCwIAAAABAA0AAABBc3NldEVuZHBvaW50AQF6AAAuAEQA" +
               "UHoAAAAADP////8BAf////8AAAAAFWDJCwIAAAAbAAAAV29UUHJvcGVydHlOYW1lX1BsYWNlaG9sZGVy" +
               "AQARAAAAPFdvVFByb3BlcnR5TmFtZT4BAUIAAQGOAAA/AQD0LEIAAAAAGP////8BAf////8AAAAABGQA" +
               "ECAAAAABAA8AAABIYXNXb1RDb21wb25lbnQBAY4AAC8DAAAAAA4AAABXb1RDb21wb25lbnRPZv////8A" +
               "AAAABGAAEAgAAAABABAAAABXb1RBc3NldEZpbGVUeXBlAQFuAAEANy3/////AQAAAARhggsEAAAAAQAO" +
               "AAAAQ2xvc2VBbmRVcGRhdGUBAW8AAC8BAW8AAE5vAAAAAQH/////AQAAABdgqQsCAAAAAAAOAAAASW5w" +
               "dXRBcmd1bWVudHMBAXAAAC4ARABOcAAAAJYBAAAAAQAqAQEZAAAACgAAAEZpbGVIYW5kbGUAB/////8A" +
               "AAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAA"
            );
            using (MemoryStream stream = new MemoryStream(initializationBuffer))
            {
                NodeStateCollection predefinedNodes = new NodeStateCollection();
                predefinedNodes.LoadFromBinary(context, stream, true);
                return predefinedNodes;
            }
        }
        #endregion
    }
    #endregion
}