// Copyright (c) OPC Foundation and contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace OpcPlc.CompanionSpecs.WotCon;

using System;
using System.Collections.Generic;

/// <summary>
/// Catalog of WoT protocol bindings this server understands. Surfaced verbatim on
/// <c>WoTAssetConnectionManagement.SupportedWoTBindings</c> (OPC 10100-1 §6.3.1) and
/// consulted by the CloseAndUpdate validator to reject Thing Descriptions that target
/// a known binding outside the supported set.
/// <para>
/// Binding URIs follow the W3C convention from
/// <see href="https://www.w3.org/TR/wot-binding-templates/">WoT Binding Templates</see>:
/// standardised protocol bindings live under <c>https://www.w3.org/2019/wot/{protocol}</c>;
/// vendor bindings own a private URI namespace under
/// <c>https://opcfoundation.org/&lt;product&gt;/&lt;name&gt;</c>.
/// </para>
/// </summary>
internal static class WotConBindings
{
    /// <summary>
    /// Built-in OPC PLC simulator binding. Indicates the asset is backed by mock values
    /// generated by this server — there is no real southbound protocol attached.
    /// </summary>
    public const string SimulatorBinding = "https://opcfoundation.org/OpcPlc/simulator";

    /// <summary>
    /// All WoT bindings this server actually implements. Surfaced verbatim on the
    /// <c>SupportedWoTBindings</c> Variable.
    /// </summary>
    public static readonly string[] SupportedBindings = new[] { SimulatorBinding };

    /// <summary>
    /// Catalog of binding URIs this server recognises as protocol bindings — the
    /// W3C-registered standardised bindings (per the W3C
    /// <see href="https://www.w3.org/TR/wot-binding-templates/">Binding Templates</see>
    /// registry) plus our vendor binding.
    /// <para>
    /// The validator uses exact-match against this set to decide whether a TD
    /// <c>@context</c> entry is a binding declaration at all. Entries here that are
    /// not in <see cref="SupportedBindings"/> cause <c>Bad_NotSupported</c>; entries
    /// outside this set (W3C TD base context, semantic vocabularies, unknown URIs)
    /// are ignored so unrelated TDs keep round-tripping.
    /// </para>
    /// </summary>
    public static readonly HashSet<string> KnownBindings = new(StringComparer.Ordinal)
    {
        // W3C standardised binding templates (https://www.w3.org/TR/wot-binding-templates/).
        "https://www.w3.org/2019/wot/http",
        "https://www.w3.org/2011/http",
        "https://www.w3.org/2019/wot/coap",
        "https://www.w3.org/2019/wot/mqtt",
        "https://www.w3.org/2019/wot/modbus",
        "https://www.w3.org/2019/wot/opcua",
        "https://www.w3.org/2019/wot/opcda",
        "https://www.w3.org/2019/wot/s7",
        "https://www.w3.org/2019/wot/ads",
        "https://www.w3.org/2019/wot/ocpp",
        "https://www.w3.org/2019/wot/eip",
        "https://www.w3.org/2019/wot/mcp",
        "https://www.w3.org/2019/wot/matter",
        "https://www.w3.org/2019/wot/iec61850",
        "https://www.w3.org/2019/wot/lorawan",
        "http://www.w3.org/2022/bacnet",

        // Vendor binding implemented by this server.
        SimulatorBinding,
    };
}
