stages:
- stage: build
  displayName: 'Build and Test Code'
  jobs:
  - template: tools/templates/ci.yml
- stage: images
  displayName: 'Build Images'
  dependsOn:
  - build
  jobs:
  - template: tools/templates/acrbuild.yml
- stage: coverage 
  displayName: 'Code Coverage'
  condition: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}
  dependsOn:
  - build
  jobs:
  - template: tools/templates/cc.yml