variables:
  OpcUaDebugNuGetFeed: 'https://pkgs.dev.azure.com/msazure/One/_packaging/aio-brokers/nuget/v3/index.json'

stages:
- stage: build
  displayName: 'Build and Test Code'
  jobs:
  - template: tools/templates/ci.yml
- stage: images
  displayName: 'Build Images'
  dependsOn:
  - build
  jobs:
  - template: tools/templates/acrbuild.yml
