/* ========================================================================
 * Copyright (c) 2005-2021 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.Runtime.Serialization;
using Opc.Ua;
using Opc.Ua.DI;

namespace BoilerModel2
{
    #region Boiler2TypeState Class
    #if (!OPCUA_EXCLUDE_Boiler2TypeState)
    /// <remarks />
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Opc.Ua.ModelCompiler", "1.0.0.0")]
    public partial class Boiler2TypeState : DeviceTypeState
    {
        #region Constructors
        /// <remarks />
        public Boiler2TypeState(NodeState parent) : base(parent)
        {
        }

        /// <remarks />
        protected override NodeId GetDefaultTypeDefinitionId(NamespaceTable namespaceUris)
        {
            return Opc.Ua.NodeId.Create(BoilerModel2.ObjectTypes.Boiler2Type, BoilerModel2.Namespaces.Boiler2, namespaceUris);
        }

        #if (!OPCUA_EXCLUDE_InitializationStrings)
        /// <remarks />
        protected override void Initialize(ISystemContext context)
        {
            base.Initialize(context);
            Initialize(context, InitializationString);
            InitializeOptionalChildren(context);
        }

        /// <remarks />
        protected override void Initialize(ISystemContext context, NodeState source)
        {
            InitializeOptionalChildren(context);
            base.Initialize(context, source);
        }

        /// <remarks />
        protected override void InitializeOptionalChildren(ISystemContext context)
        {
            base.InitializeOptionalChildren(context);
        }

        #region Initialization String
        private const string InitializationString =
           "AgAAACYAAABodHRwOi8vbWljcm9zb2Z0LmNvbS9PcGMvT3BjUGxjL0JvaWxlch8AAABodHRwOi8vb3Bj" +
           "Zm91bmRhdGlvbi5vcmcvVUEvREkv/////wRggAIBAAAAAQATAAAAQm9pbGVyMlR5cGVJbnN0YW5jZQEB" +
           "6AMBAegD6AMAAP////8SAAAAJGCACgEAAAACAAwAAABQYXJhbWV0ZXJTZXQBAZYTAwAAAAAXAAAARmxh" +
           "dCBsaXN0IG9mIFBhcmFtZXRlcnMALwA6lhMAAP////8JAAAAFWCJCgIAAAABABYAAABUZW1wZXJhdHVy" +
           "ZUNoYW5nZVNwZWVkAQGJFwAvAD+JFwAAAAr/////AwP/////AAAAABVgqQoCAAAAAQAPAAAAQmFzZVRl" +
           "bXBlcmF0dXJlAQGKFwAvAD+KFwAACgAAoEEACv////8DA/////8AAAAAFWCJCgIAAAABABEAAABUYXJn" +
           "ZXRUZW1wZXJhdHVyZQEBixcALwA/ixcAAAAK/////wMD/////wAAAAAVYKkKAgAAAAEAEwAAAE1haW50" +
           "ZW5hbmNlSW50ZXJ2YWwBAYwXAC8AP4wXAAAHLAEAAAAH/////wMD/////wAAAAAVYIkKAgAAAAEAHgAA" +
           "AE92ZXJoZWF0ZWRUaHJlc2hvbGRUZW1wZXJhdHVyZQEBjRcALwA/jRcAAAAK/////wMD/////wAAAAAV" +
           "YIkKAgAAAAEACwAAAEhlYXRlclN0YXRlAQGOFwAvAD+OFwAAAAH/////AwP/////AAAAABVgqQoCAAAA" +
           "AQASAAAAQ3VycmVudFRlbXBlcmF0dXJlAQGPFwAvAD+PFwAACgAAoEEACv////8BAf////8AAAAAFWCJ" +
           "CgIAAAABAAoAAABPdmVyaGVhdGVkAQGRFwAvAD+RFwAAAAH/////AQH/////AAAAABVgqQoCAAAAAQAQ" +
           "AAAAT3ZlcmhlYXRJbnRlcnZhbAEBkhcALwA/khcAAAd4AAAAAAf/////AwP/////AAAAACRggAoBAAAA" +
           "AgAJAAAATWV0aG9kU2V0AQGVEwMAAAAAFAAAAEZsYXQgbGlzdCBvZiBNZXRob2RzAC8AOpUTAAD/////" +
           "AQAAAARhggoEAAAAAQAGAAAAU3dpdGNoAQFYGwAvAQFYG1gbAAABAf////8CAAAAN2CpCgIAAAAAAA4A" +
           "AABJbnB1dEFyZ3VtZW50cwEBhxcDAAAAAEAAAAB0aGUgZGVmaW5pdGlvbiBvZiB0aGUgaW5wdXQgYXJn" +
           "dW1lbnQgb2YgbWV0aG9kIDI6Qm9pbGVyLjI6U3dpdGNoAC4ARIcXAACWAQAAAAEAKgEBEQAAAAIAAABP" +
           "bgAB/////wAAAAAAAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAA3YIkKAgAAAAAADwAAAE91dHB1dEFy" +
           "Z3VtZW50cwEBiBcDAAAAAEIAAAB0aGUgZGVmaW5pdGlvbiBvZiB0aGUgb3V0cHV0IGFyZ3VtZW50cyBv" +
           "ZiBtZXRob2QgMjpCb2lsZXIuMjpTd2l0Y2gALgBEiBcAAAEAKAEBAAAAAQAAAAAAAAABAf////8AAAAA" +
           "NWCJCgIAAAACAAwAAABNYW51ZmFjdHVyZXIBAXsXAwAAAAAwAAAATmFtZSBvZiB0aGUgY29tcGFueSB0" +
           "aGF0IG1hbnVmYWN0dXJlZCB0aGUgZGV2aWNlAC4ARHsXAAAAFf////8BAf////8AAAAAFWCJCgIAAAAC" +
           "AA8AAABNYW51ZmFjdHVyZXJVcmkBAXwXAC4ARHwXAAAADP////8BAf////8AAAAANWCJCgIAAAACAAUA" +
           "AABNb2RlbAEBfRcDAAAAABgAAABNb2RlbCBuYW1lIG9mIHRoZSBkZXZpY2UALgBEfRcAAAAV/////wEB" +
           "/////wAAAAA1YIkKAgAAAAIAEAAAAEhhcmR3YXJlUmV2aXNpb24BAX8XAwAAAAAsAAAAUmV2aXNpb24g" +
           "bGV2ZWwgb2YgdGhlIGhhcmR3YXJlIG9mIHRoZSBkZXZpY2UALgBEfxcAAAAM/////wEB/////wAAAAA1" +
           "YIkKAgAAAAIAEAAAAFNvZnR3YXJlUmV2aXNpb24BAYAXAwAAAAA1AAAAUmV2aXNpb24gbGV2ZWwgb2Yg" +
           "dGhlIHNvZnR3YXJlL2Zpcm13YXJlIG9mIHRoZSBkZXZpY2UALgBEgBcAAAAM/////wEB/////wAAAAA1" +
           "YIkKAgAAAAIADgAAAERldmljZVJldmlzaW9uAQGBFwMAAAAAJAAAAE92ZXJhbGwgcmV2aXNpb24gbGV2" +
           "ZWwgb2YgdGhlIGRldmljZQAuAESBFwAAAAz/////AQH/////AAAAABVgiQoCAAAAAgALAAAAUHJvZHVj" +
           "dENvZGUBAX4XAC4ARH4XAAAADP////8BAf////8AAAAANWCJCgIAAAACAAwAAABEZXZpY2VNYW51YWwB" +
           "AYIXAwAAAABaAAAAQWRkcmVzcyAocGF0aG5hbWUgaW4gdGhlIGZpbGUgc3lzdGVtIG9yIGEgVVJMIHwg" +
           "V2ViIGFkZHJlc3MpIG9mIHVzZXIgbWFudWFsIGZvciB0aGUgZGV2aWNlAC4ARIIXAAAADP////8BAf//" +
           "//8AAAAAFWCJCgIAAAACAAsAAABEZXZpY2VDbGFzcwEBgxcALgBEgxcAAAAM/////wEB/////wAAAAA1" +
           "YIkKAgAAAAIADAAAAFNlcmlhbE51bWJlcgEBhBcDAAAAAE0AAABJZGVudGlmaWVyIHRoYXQgdW5pcXVl" +
           "bHkgaWRlbnRpZmllcywgd2l0aGluIGEgbWFudWZhY3R1cmVyLCBhIGRldmljZSBpbnN0YW5jZQAuAESE" +
           "FwAAAAz/////AQH/////AAAAABVgiQoCAAAAAgASAAAAUHJvZHVjdEluc3RhbmNlVXJpAQGFFwAuAESF" +
           "FwAAAAz/////AQH/////AAAAADVgiQoCAAAAAgAPAAAAUmV2aXNpb25Db3VudGVyAQGGFwMAAAAAaQAA" +
           "AEFuIGluY3JlbWVudGFsIGNvdW50ZXIgaW5kaWNhdGluZyB0aGUgbnVtYmVyIG9mIHRpbWVzIHRoZSBz" +
           "dGF0aWMgZGF0YSB3aXRoaW4gdGhlIERldmljZSBoYXMgYmVlbiBtb2RpZmllZAAuAESGFwAAAAb/////" +
           "AQH/////AAAAABVgiQoCAAAAAgAHAAAAQXNzZXRJZAEBeBcALgBEeBcAAAAM/////wEB/////wAAAAAV" +
           "YIkKAgAAAAIADQAAAENvbXBvbmVudE5hbWUBAXkXAC4ARHkXAAAAFf////8BAf////8AAAAAFWCJCgIA" +
           "AAACAAwAAABEZXZpY2VIZWFsdGgBAXoXAC8AP3oXAAABAmQY/////wEB/////wAAAAAEYIAKAQAAAAIA" +
           "EgAAAERldmljZUhlYWx0aEFsYXJtcwEBihMALwA9ihMAAP////8EAAAAhGCACgEAAAABAAwAAABGYWls" +
           "dXJlQWxhcm0BAYsTACMBArw7ixMAAAH/////GwAAABVgiQgCAAAAAAAHAAAARXZlbnRJZAEBAAAALgBE" +
           "AA//////AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRUeXBlAQEAAAAuAEQAEf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAA" +
           "AAoAAABTb3VyY2VOYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAQAAABUaW1lAQEA" +
           "AAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB" +
           "/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4ARAAV/////wEB/////wAAAAAV" +
           "YIkIAgAAAAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf////8BAf////8AAAAAFWCJCAIAAAAAABAAAABD" +
           "b25kaXRpb25DbGFzc0lkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABIAAABDb25kaXRp" +
           "b25DbGFzc05hbWUBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAADQAAAENvbmRpdGlvbk5h" +
           "bWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAEJyYW5jaElkAQEAAAAuAEQAEf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAADAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAAEBAAABAAAAFWCJ" +
           "CAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEB" +
           "AAAALwEAKiMAE/////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4A" +
           "RAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFzdFNldmVyaXR5AQEAAAAvAQAqIwAF////" +
           "/wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAqIwAV/////wEB/////wEAAAAVYIkIAgAA" +
           "AAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAwA" +
           "AABDbGllbnRVc2VySWQBAQAAAC4ARAAM/////wEB/////wAAAAAEYYIIBAAAAAAABwAAAERpc2FibGUB" +
           "AQAAAC8BAEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAGAAAARW5hYmxlAQEAAAAvAQBDIwEB" +
           "AQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENvbW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5" +
           "CwABAA0LAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAA" +
           "BwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0" +
           "byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50" +
           "IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAA" +
           "AAoAAABBY2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAA" +
           "AgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAABGGCCAQAAAAAAAsAAABBY2tub3dsZWRnZQEBAAAA" +
           "LwEAlyMBAQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBE" +
           "lgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRpZmllciBm" +
           "b3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAk" +
           "AAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAAAAEB////" +
           "/wAAAAAVYIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEA" +
           "AAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAkAAABJ" +
           "bnB1dE5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAAEwAAAFN1cHByZXNzZWRPclNo" +
           "ZWx2ZWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAE5vcm1hbFN0YXRlAQEAAAAu" +
           "AEQAEf////8BAf////8AAAAAhGCACgEAAAABABIAAABDaGVja0Z1bmN0aW9uQWxhcm0BAYwTACMBAlE8" +
           "jBMAAAH/////GwAAABVgiQgCAAAAAAAHAAAARXZlbnRJZAEBAAAALgBEAA//////AQH/////AAAAABVg" +
           "iQgCAAAAAAAJAAAARXZlbnRUeXBlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABT" +
           "b3VyY2VOb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOYW1lAQEA" +
           "AAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAQAAABUaW1lAQEAAAAuAEQBACYB/////wEB////" +
           "/wAAAAAVYIkIAgAAAAAACwAAAFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAFNldmVy" +
           "aXR5AQEAAAAuAEQABf////8BAf////8AAAAAFWCJCAIAAAAAABAAAABDb25kaXRpb25DbGFzc0lkAQEA" +
           "AAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABIAAABDb25kaXRpb25DbGFzc05hbWUBAQAAAC4A" +
           "RAAV/////wEB/////wAAAAAVYIkIAgAAAAAADQAAAENvbmRpdGlvbk5hbWUBAQAAAC4ARAAM/////wEB" +
           "/////wAAAAAVYIkIAgAAAAAACAAAAEJyYW5jaElkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIA" +
           "AAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAEVuYWJsZWRT" +
           "dGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAAEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAA" +
           "LgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEBAAAALwEAKiMAE/////8BAf//" +
           "//8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAA" +
           "ABVgiQgCAAAAAAAMAAAATGFzdFNldmVyaXR5AQEAAAAvAQAqIwAF/////wEB/////wEAAAAVYIkIAgAA" +
           "AAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAcA" +
           "AABDb21tZW50AQEAAAAvAQAqIwAV/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVz" +
           "dGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABDbGllbnRVc2VySWQBAQAA" +
           "AC4ARAAM/////wEB/////wAAAAAEYYIIBAAAAAAABwAAAERpc2FibGUBAQAAAC8BAEQjAQEBAAAAAQD5" +
           "CwABAPMKAAAAAARhgggEAAAAAAAGAAAARW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA+QsAAQDzCgAAAAAE" +
           "YYIIBAAAAAAACgAAAEFkZENvbW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5CwABAA0LAQAAABdgqQgCAAAA" +
           "AAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50SWQAD/////8A" +
           "AAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50LgEAKgEBQgAA" +
           "AAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0byB0aGUgY29u" +
           "ZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAAAAoAAABBY2tlZFN0YXRlAQEA" +
           "AAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf//" +
           "//8BAf////8AAAAABGGCCAQAAAAAAAsAAABBY2tub3dsZWRnZQEBAAAALwEAlyMBAQEAAAABAPkLAAEA" +
           "8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoBAUYAAAAHAAAA" +
           "RXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2ZW50IHRvIGNv" +
           "bW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8g" +
           "YWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkIAgAAAAAACwAA" +
           "AEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAA" +
           "AElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAkAAABJbnB1dE5vZGUBAQAAAC4ARAAR" +
           "/////wEB/////wAAAAAVYIkIAgAAAAAAEwAAAFN1cHByZXNzZWRPclNoZWx2ZWQBAQAAAC4ARAAB////" +
           "/wEB/////wAAAAAVYIkIAgAAAAAACwAAAE5vcm1hbFN0YXRlAQEAAAAuAEQAEf////8BAf////8AAAAA" +
           "hGCACgEAAAABAAwAAABPZmZTcGVjQWxhcm0BAY0TACMBAuY8jRMAAAH/////GwAAABVgiQgCAAAAAAAH" +
           "AAAARXZlbnRJZAEBAAAALgBEAA//////AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRUeXBlAQEA" +
           "AAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQAEf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJ" +
           "CAIAAAAAAAQAAABUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAFJlY2Vp" +
           "dmVUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4A" +
           "RAAV/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAABAAAABDb25kaXRpb25DbGFzc0lkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJ" +
           "CAIAAAAAABIAAABDb25kaXRpb25DbGFzc05hbWUBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAA" +
           "AAAADQAAAENvbmRpdGlvbk5hbWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAEJy" +
           "YW5jaElkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB" +
           "/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEA" +
           "AAABACwjAAEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgC" +
           "AAAAAAAHAAAAUXVhbGl0eQEBAAAALwEAKiMAE/////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3Vy" +
           "Y2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFzdFNldmVy" +
           "aXR5AQEAAAAvAQAqIwAF/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEB" +
           "AAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAqIwAV////" +
           "/wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAwAAABDbGllbnRVc2VySWQBAQAAAC4ARAAM/////wEB/////wAAAAAEYYII" +
           "BAAAAAAABwAAAERpc2FibGUBAQAAAC8BAEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAGAAAA" +
           "RW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENvbW1lbnQB" +
           "AQAAAC8BAEUjAQEBAAAAAQD5CwABAA0LAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAA" +
           "AC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZp" +
           "ZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMA" +
           "AAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAAB" +
           "Af////8AAAAAFWCJCAIAAAAAAAoAAABBY2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMB" +
           "AQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAABGGCCAQAAAAAAAsA" +
           "AABBY2tub3dsZWRnZQEBAAAALwEAlyMBAQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1" +
           "dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgA" +
           "AABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1l" +
           "bnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAo" +
           "AQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV" +
           "/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAkAAABJbnB1dE5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "EwAAAFN1cHByZXNzZWRPclNoZWx2ZWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAACwAA" +
           "AE5vcm1hbFN0YXRlAQEAAAAuAEQAEf////8BAf////8AAAAAhGCACgEAAAABABgAAABNYWludGVuYW5j" +
           "ZVJlcXVpcmVkQWxhcm0BAY4TACMBAns9jhMAAAH/////GwAAABVgiQgCAAAAAAAHAAAARXZlbnRJZAEB" +
           "AAAALgBEAA//////AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRUeXBlAQEAAAAuAEQAEf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJ" +
           "CAIAAAAAAAoAAABTb3VyY2VOYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAQAAABU" +
           "aW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAFJlY2VpdmVUaW1lAQEAAAAu" +
           "AEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4ARAAV/////wEB////" +
           "/wAAAAAVYIkIAgAAAAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf////8BAf////8AAAAAFWCJCAIAAAAA" +
           "ABAAAABDb25kaXRpb25DbGFzc0lkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABIAAABD" +
           "b25kaXRpb25DbGFzc05hbWUBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAADQAAAENvbmRp" +
           "dGlvbk5hbWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAEJyYW5jaElkAQEAAAAu" +
           "AEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB/////wEB/////wAA" +
           "AAAVYIkIAgAAAAAADAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAAEBAAAB" +
           "AAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAAUXVh" +
           "bGl0eQEBAAAALwEAKiMAE/////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXAB" +
           "AQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFzdFNldmVyaXR5AQEAAAAvAQAq" +
           "IwAF/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAqIwAV/////wEB/////wEAAAAV" +
           "YIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIA" +
           "AAAAAAwAAABDbGllbnRVc2VySWQBAQAAAC4ARAAM/////wEB/////wAAAAAEYYIIBAAAAAAABwAAAERp" +
           "c2FibGUBAQAAAC8BAEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAGAAAARW5hYmxlAQEAAAAv" +
           "AQBDIwEBAQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENvbW1lbnQBAQAAAC8BAEUjAQEB" +
           "AAAAAQD5CwABAA0LAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAq" +
           "AQFGAAAABwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBl" +
           "dmVudCB0byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBj" +
           "b21tZW50IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJ" +
           "CAIAAAAAAAoAAABBY2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkI" +
           "AgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAABGGCCAQAAAAAAAsAAABBY2tub3dsZWRn" +
           "ZQEBAAAALwEAlyMBAQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEB" +
           "AAAALgBElgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRp" +
           "ZmllciBmb3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAA" +
           "AwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAA" +
           "AAEB/////wAAAAAVYIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEA" +
           "LCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAA" +
           "AAkAAABJbnB1dE5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAAEwAAAFN1cHByZXNz" +
           "ZWRPclNoZWx2ZWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAE5vcm1hbFN0YXRl" +
           "AQEAAAAuAEQAEf////8BAf////8AAAAA";
        #endregion
        #endif
        #endregion

        #region Public Properties
        #endregion

        #region Overridden Methods
        #endregion

        #region Private Fields
        #endregion
    }
    #endif
    #endregion
}