/* ========================================================================
 * Copyright (c) 2005-2021 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.Runtime.Serialization;
using Opc.Ua;
using Opc.Ua.DI;

namespace BoilerModel2
{
    #region BoilerModel2TypeState Class
    #if (!OPCUA_EXCLUDE_BoilerModel2TypeState)
    /// <remarks />
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Opc.Ua.ModelCompiler", "1.0.0.0")]
    public partial class BoilerModel2TypeState : DeviceTypeState
    {
        #region Constructors
        /// <remarks />
        public BoilerModel2TypeState(NodeState parent) : base(parent)
        {
        }

        /// <remarks />
        protected override NodeId GetDefaultTypeDefinitionId(NamespaceTable namespaceUris)
        {
            return Opc.Ua.NodeId.Create(BoilerModel2.ObjectTypes.BoilerModel2Type, BoilerModel2.Namespaces.Boiler2, namespaceUris);
        }

        #if (!OPCUA_EXCLUDE_InitializationStrings)
        /// <remarks />
        protected override void Initialize(ISystemContext context)
        {
            base.Initialize(context);
            Initialize(context, InitializationString);
            InitializeOptionalChildren(context);
        }

        /// <remarks />
        protected override void Initialize(ISystemContext context, NodeState source)
        {
            InitializeOptionalChildren(context);
            base.Initialize(context, source);
        }

        /// <remarks />
        protected override void InitializeOptionalChildren(ISystemContext context)
        {
            base.InitializeOptionalChildren(context);
        }

        #region Initialization String
        private const string InitializationString =
           "AgAAACYAAABodHRwOi8vbWljcm9zb2Z0LmNvbS9PcGMvT3BjUGxjL0JvaWxlch8AAABodHRwOi8vb3Bj" +
           "Zm91bmRhdGlvbi5vcmcvVUEvREkv/////wRggAIBAAAAAQAYAAAAQm9pbGVyTW9kZWwyVHlwZUluc3Rh" +
           "bmNlAQHoAwEB6APoAwAA/////xIAAAAkYIAKAQAAAAIADAAAAFBhcmFtZXRlclNldAEBlhMDAAAAABcA" +
           "AABGbGF0IGxpc3Qgb2YgUGFyYW1ldGVycwAvADqWEwAA/////wkAAAAVYIkKAgAAAAEAFgAAAFRlbXBl" +
           "cmF0dXJlQ2hhbmdlU3BlZWQBAYkXAC8AP4kXAAAACv////8DA/////8AAAAAFWCpCgIAAAABAA8AAABC" +
           "YXNlVGVtcGVyYXR1cmUBAYoXAC8AP4oXAAAKAACgQQAK/////wMD/////wAAAAAVYIkKAgAAAAEAEQAA" +
           "AFRhcmdldFRlbXBlcmF0dXJlAQGLFwAvAD+LFwAAAAr/////AwP/////AAAAABVgqQoCAAAAAQATAAAA" +
           "TWFpbnRlbmFuY2VJbnRlcnZhbAEBjBcALwA/jBcAAAY8AAAAAAb/////AwP/////AAAAABVgiQoCAAAA" +
           "AQAeAAAAT3ZlcmhlYXRlZFRocmVzaG9sZFRlbXBlcmF0dXJlAQGNFwAvAD+NFwAAAAr/////AwP/////" +
           "AAAAABVgiQoCAAAAAQALAAAASGVhdGVyU3RhdGUBAY4XAC8AP44XAAAAAf////8DA/////8AAAAAFWCp" +
           "CgIAAAABABIAAABDdXJyZW50VGVtcGVyYXR1cmUBAY8XAC8AP48XAAAKAACgQQAK/////wEB/////wAA" +
           "AAAVYIkKAgAAAAEACAAAAFByZXNzdXJlAQGQFwAvAD+QFwAAAAr/////AQH/////AAAAABVgiQoCAAAA" +
           "AQAKAAAAT3ZlcmhlYXRlZAEBkRcALwA/kRcAAAAB/////wEB/////wAAAAAkYIAKAQAAAAIACQAAAE1l" +
           "dGhvZFNldAEBlRMDAAAAABQAAABGbGF0IGxpc3Qgb2YgTWV0aG9kcwAvADqVEwAA/////wEAAAAEYYIK" +
           "BAAAAAEABgAAAFN3aXRjaAEBWBsALwEBWBtYGwAAAQH/////AgAAADdgqQoCAAAAAAAOAAAASW5wdXRB" +
           "cmd1bWVudHMBAYcXAwAAAABAAAAAdGhlIGRlZmluaXRpb24gb2YgdGhlIGlucHV0IGFyZ3VtZW50IG9m" +
           "IG1ldGhvZCAyOkJvaWxlci4yOlN3aXRjaAAuAESHFwAAlgEAAAABACoBAREAAAACAAAAT24AAf////8A" +
           "AAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAN2CJCgIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMB" +
           "AYgXAwAAAABCAAAAdGhlIGRlZmluaXRpb24gb2YgdGhlIG91dHB1dCBhcmd1bWVudHMgb2YgbWV0aG9k" +
           "IDI6Qm9pbGVyLjI6U3dpdGNoAC4ARIgXAAABACgBAQAAAAEAAAAAAAAAAQH/////AAAAADVgiQoCAAAA" +
           "AgAMAAAATWFudWZhY3R1cmVyAQF7FwMAAAAAMAAAAE5hbWUgb2YgdGhlIGNvbXBhbnkgdGhhdCBtYW51" +
           "ZmFjdHVyZWQgdGhlIGRldmljZQAuAER7FwAAABX/////AQH/////AAAAABVgiQoCAAAAAgAPAAAATWFu" +
           "dWZhY3R1cmVyVXJpAQF8FwAuAER8FwAAAAz/////AQH/////AAAAADVgiQoCAAAAAgAFAAAATW9kZWwB" +
           "AX0XAwAAAAAYAAAATW9kZWwgbmFtZSBvZiB0aGUgZGV2aWNlAC4ARH0XAAAAFf////8BAf////8AAAAA" +
           "NWCJCgIAAAACABAAAABIYXJkd2FyZVJldmlzaW9uAQF/FwMAAAAALAAAAFJldmlzaW9uIGxldmVsIG9m" +
           "IHRoZSBoYXJkd2FyZSBvZiB0aGUgZGV2aWNlAC4ARH8XAAAADP////8BAf////8AAAAANWCJCgIAAAAC" +
           "ABAAAABTb2Z0d2FyZVJldmlzaW9uAQGAFwMAAAAANQAAAFJldmlzaW9uIGxldmVsIG9mIHRoZSBzb2Z0" +
           "d2FyZS9maXJtd2FyZSBvZiB0aGUgZGV2aWNlAC4ARIAXAAAADP////8BAf////8AAAAANWCJCgIAAAAC" +
           "AA4AAABEZXZpY2VSZXZpc2lvbgEBgRcDAAAAACQAAABPdmVyYWxsIHJldmlzaW9uIGxldmVsIG9mIHRo" +
           "ZSBkZXZpY2UALgBEgRcAAAAM/////wEB/////wAAAAAVYIkKAgAAAAIACwAAAFByb2R1Y3RDb2RlAQF+" +
           "FwAuAER+FwAAAAz/////AQH/////AAAAADVgiQoCAAAAAgAMAAAARGV2aWNlTWFudWFsAQGCFwMAAAAA" +
           "WgAAAEFkZHJlc3MgKHBhdGhuYW1lIGluIHRoZSBmaWxlIHN5c3RlbSBvciBhIFVSTCB8IFdlYiBhZGRy" +
           "ZXNzKSBvZiB1c2VyIG1hbnVhbCBmb3IgdGhlIGRldmljZQAuAESCFwAAAAz/////AQH/////AAAAABVg" +
           "iQoCAAAAAgALAAAARGV2aWNlQ2xhc3MBAYMXAC4ARIMXAAAADP////8BAf////8AAAAANWCJCgIAAAAC" +
           "AAwAAABTZXJpYWxOdW1iZXIBAYQXAwAAAABNAAAASWRlbnRpZmllciB0aGF0IHVuaXF1ZWx5IGlkZW50" +
           "aWZpZXMsIHdpdGhpbiBhIG1hbnVmYWN0dXJlciwgYSBkZXZpY2UgaW5zdGFuY2UALgBEhBcAAAAM////" +
           "/wEB/////wAAAAAVYIkKAgAAAAIAEgAAAFByb2R1Y3RJbnN0YW5jZVVyaQEBhRcALgBEhRcAAAAM////" +
           "/wEB/////wAAAAA1YIkKAgAAAAIADwAAAFJldmlzaW9uQ291bnRlcgEBhhcDAAAAAGkAAABBbiBpbmNy" +
           "ZW1lbnRhbCBjb3VudGVyIGluZGljYXRpbmcgdGhlIG51bWJlciBvZiB0aW1lcyB0aGUgc3RhdGljIGRh" +
           "dGEgd2l0aGluIHRoZSBEZXZpY2UgaGFzIGJlZW4gbW9kaWZpZWQALgBEhhcAAAAG/////wEB/////wAA" +
           "AAAVYIkKAgAAAAIABwAAAEFzc2V0SWQBAXgXAC4ARHgXAAAADP////8BAf////8AAAAAFWCJCgIAAAAC" +
           "AA0AAABDb21wb25lbnROYW1lAQF5FwAuAER5FwAAABX/////AQH/////AAAAABVgiQoCAAAAAgAMAAAA" +
           "RGV2aWNlSGVhbHRoAQF6FwAvAD96FwAAAQJkGP////8BAf////8AAAAABGCACgEAAAACABIAAABEZXZp" +
           "Y2VIZWFsdGhBbGFybXMBAYoTAC8APYoTAAD/////BAAAAARggAoBAAAAAQAMAAAARmFpbHVyZUFsYXJt" +
           "AQGLEwAjAQK8O4sTAAD/////GwAAABVgiQgCAAAAAAAHAAAARXZlbnRJZAEBAAAALgBEAA//////AQH/" +
           "////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRUeXBlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIA" +
           "AAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3Vy" +
           "Y2VOYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAQAAABUaW1lAQEAAAAuAEQBACYB" +
           "/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB/////wEB////" +
           "/wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "CAAAAFNldmVyaXR5AQEAAAAuAEQABf////8BAf////8AAAAAFWCJCAIAAAAAABAAAABDb25kaXRpb25D" +
           "bGFzc0lkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABIAAABDb25kaXRpb25DbGFzc05h" +
           "bWUBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAADQAAAENvbmRpdGlvbk5hbWUBAQAAAC4A" +
           "RAAM/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAEJyYW5jaElkAQEAAAAuAEQAEf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAADAAA" +
           "AEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAAEBAAABAAAAFWCJCAIAAAAAAAIA" +
           "AABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEBAAAALwEAKiMA" +
           "E/////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////" +
           "AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFzdFNldmVyaXR5AQEAAAAvAQAqIwAF/////wEB/////wEA" +
           "AAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJ" +
           "CAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAqIwAV/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNv" +
           "dXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABDbGllbnRV" +
           "c2VySWQBAQAAAC4ARAAM/////wEB/////wAAAAAEYYIIBAAAAAAABwAAAERpc2FibGUBAQAAAC8BAEQj" +
           "AQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAGAAAARW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA+QsA" +
           "AQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENvbW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5CwABAA0LAQAA" +
           "ABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50" +
           "SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50" +
           "LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0" +
           "byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAAAAoAAABBY2tl" +
           "ZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEA" +
           "AAAuAEQAAf////8BAf////8AAAAABGGCCAQAAAAAAAsAAABBY2tub3dsZWRnZQEBAAAALwEAlyMBAQEA" +
           "AAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoB" +
           "AUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2" +
           "ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNv" +
           "bW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkI" +
           "AgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkI" +
           "AgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAkAAABJbnB1dE5vZGUB" +
           "AQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAAEwAAAFN1cHByZXNzZWRPclNoZWx2ZWQBAQAA" +
           "AC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAE5vcm1hbFN0YXRlAQEAAAAuAEQAEf////8B" +
           "Af////8AAAAABGCACgEAAAABABIAAABDaGVja0Z1bmN0aW9uQWxhcm0BAYwTACMBAlE8jBMAAP////8b" +
           "AAAAFWCJCAIAAAAAAAcAAABFdmVudElkAQEAAAAuAEQAD/////8BAf////8AAAAAFWCJCAIAAAAAAAkA" +
           "AABFdmVudFR5cGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAACgAAAFNvdXJjZU5vZGUB" +
           "AQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAACgAAAFNvdXJjZU5hbWUBAQAAAC4ARAAM////" +
           "/wEB/////wAAAAAVYIkIAgAAAAAABAAAAFRpbWUBAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgC" +
           "AAAAAAALAAAAUmVjZWl2ZVRpbWUBAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAA" +
           "TWVzc2FnZQEBAAAALgBEABX/////AQH/////AAAAABVgiQgCAAAAAAAIAAAAU2V2ZXJpdHkBAQAAAC4A" +
           "RAAF/////wEB/////wAAAAAVYIkIAgAAAAAAEAAAAENvbmRpdGlvbkNsYXNzSWQBAQAAAC4ARAAR////" +
           "/wEB/////wAAAAAVYIkIAgAAAAAAEgAAAENvbmRpdGlvbkNsYXNzTmFtZQEBAAAALgBEABX/////AQH/" +
           "////AAAAABVgiQgCAAAAAAANAAAAQ29uZGl0aW9uTmFtZQEBAAAALgBEAAz/////AQH/////AAAAABVg" +
           "iQgCAAAAAAAIAAAAQnJhbmNoSWQBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAABgAAAFJl" +
           "dGFpbgEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAARW5hYmxlZFN0YXRlAQEAAAAv" +
           "AQAjIwAV/////wEBAQAAAAEALCMAAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAAAcAAABRdWFsaXR5AQEAAAAvAQAqIwAT/////wEB/////wEAAAAVYIkI" +
           "AgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAA" +
           "AAwAAABMYXN0U2V2ZXJpdHkBAQAAAC8BACojAAX/////AQH/////AQAAABVgiQgCAAAAAAAPAAAAU291" +
           "cmNlVGltZXN0YW1wAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAENvbW1lbnQB" +
           "AQAAAC8BACojABX/////AQH/////AQAAABVgiQgCAAAAAAAPAAAAU291cmNlVGltZXN0YW1wAQEAAAAu" +
           "AEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAENsaWVudFVzZXJJZAEBAAAALgBEAAz/////" +
           "AQH/////AAAAAARhgggEAAAAAAAHAAAARGlzYWJsZQEBAAAALwEARCMBAQEAAAABAPkLAAEA8woAAAAA" +
           "BGGCCAQAAAAAAAYAAABFbmFibGUBAQAAAC8BAEMjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAK" +
           "AAAAQWRkQ29tbWVudAEBAAAALwEARSMBAQEAAAABAPkLAAEADQsBAAAAF2CpCAIAAAAAAA4AAABJbnB1" +
           "dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgA" +
           "AABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1l" +
           "bnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAo" +
           "AQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkIAgAAAAAACgAAAEFja2VkU3RhdGUBAQAAAC8BACMjABX/" +
           "////AQEBAAAAAQAsIwEBAQAAAQAAABVgiQgCAAAAAAACAAAASWQBAQAAAC4ARAAB/////wEB/////wAA" +
           "AAAEYYIIBAAAAAAACwAAAEFja25vd2xlZGdlAQEAAAAvAQCXIwEBAQAAAAEA+QsAAQDwIgEAAAAXYKkI" +
           "AgAAAAAADgAAAElucHV0QXJndW1lbnRzAQEAAAAuAESWAgAAAAEAKgEBRgAAAAcAAABFdmVudElkAA//" +
           "////AAAAAAMAAAAAKAAAAFRoZSBpZGVudGlmaWVyIGZvciB0aGUgZXZlbnQgdG8gY29tbWVudC4BACoB" +
           "AUIAAAAHAAAAQ29tbWVudAAV/////wAAAAADAAAAACQAAABUaGUgY29tbWVudCB0byBhZGQgdG8gdGhl" +
           "IGNvbmRpdGlvbi4BACgBAQAAAAEAAAAAAAAAAQH/////AAAAABVgiQgCAAAAAAALAAAAQWN0aXZlU3Rh" +
           "dGUBAQAAAC8BACMjABX/////AQEBAAAAAQAsIwEBAQAAAQAAABVgiQgCAAAAAAACAAAASWQBAQAAAC4A" +
           "RAAB/////wEB/////wAAAAAVYIkIAgAAAAAACQAAAElucHV0Tm9kZQEBAAAALgBEABH/////AQH/////" +
           "AAAAABVgiQgCAAAAAAATAAAAU3VwcHJlc3NlZE9yU2hlbHZlZAEBAAAALgBEAAH/////AQH/////AAAA" +
           "ABVgiQgCAAAAAAALAAAATm9ybWFsU3RhdGUBAQAAAC4ARAAR/////wEB/////wAAAAAEYIAKAQAAAAEA" +
           "DAAAAE9mZlNwZWNBbGFybQEBjRMAIwEC5jyNEwAA/////xsAAAAVYIkIAgAAAAAABwAAAEV2ZW50SWQB" +
           "AQAAAC4ARAAP/////wEB/////wAAAAAVYIkIAgAAAAAACQAAAEV2ZW50VHlwZQEBAAAALgBEABH/////" +
           "AQH/////AAAAABVgiQgCAAAAAAAKAAAAU291cmNlTm9kZQEBAAAALgBEABH/////AQH/////AAAAABVg" +
           "iQgCAAAAAAAKAAAAU291cmNlTmFtZQEBAAAALgBEAAz/////AQH/////AAAAABVgiQgCAAAAAAAEAAAA" +
           "VGltZQEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAsAAABSZWNlaXZlVGltZQEBAAAA" +
           "LgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAcAAABNZXNzYWdlAQEAAAAuAEQAFf////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAgAAABTZXZlcml0eQEBAAAALgBEAAX/////AQH/////AAAAABVgiQgCAAAA" +
           "AAAQAAAAQ29uZGl0aW9uQ2xhc3NJZAEBAAAALgBEABH/////AQH/////AAAAABVgiQgCAAAAAAASAAAA" +
           "Q29uZGl0aW9uQ2xhc3NOYW1lAQEAAAAuAEQAFf////8BAf////8AAAAAFWCJCAIAAAAAAA0AAABDb25k" +
           "aXRpb25OYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAgAAABCcmFuY2hJZAEBAAAA" +
           "LgBEABH/////AQH/////AAAAABVgiQgCAAAAAAAGAAAAUmV0YWluAQEAAAAuAEQAAf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAwAAABFbmFibGVkU3RhdGUBAQAAAC8BACMjABX/////AQEBAAAAAQAsIwABAQAA" +
           "AQAAABVgiQgCAAAAAAACAAAASWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAFF1" +
           "YWxpdHkBAQAAAC8BACojABP/////AQH/////AQAAABVgiQgCAAAAAAAPAAAAU291cmNlVGltZXN0YW1w" +
           "AQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAExhc3RTZXZlcml0eQEBAAAALwEA" +
           "KiMABf////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/" +
           "////AQH/////AAAAABVgiQgCAAAAAAAHAAAAQ29tbWVudAEBAAAALwEAKiMAFf////8BAf////8BAAAA" +
           "FWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgC" +
           "AAAAAAAMAAAAQ2xpZW50VXNlcklkAQEAAAAuAEQADP////8BAf////8AAAAABGGCCAQAAAAAAAcAAABE" +
           "aXNhYmxlAQEAAAAvAQBEIwEBAQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAABgAAAEVuYWJsZQEBAAAA" +
           "LwEAQyMBAQEAAAABAPkLAAEA8woAAAAABGGCCAQAAAAAAAoAAABBZGRDb21tZW50AQEAAAAvAQBFIwEB" +
           "AQAAAAEA+QsAAQANCwEAAAAXYKkIAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQEAAAAuAESWAgAAAAEA" +
           "KgEBRgAAAAcAAABFdmVudElkAA//////AAAAAAMAAAAAKAAAAFRoZSBpZGVudGlmaWVyIGZvciB0aGUg" +
           "ZXZlbnQgdG8gY29tbWVudC4BACoBAUIAAAAHAAAAQ29tbWVudAAV/////wAAAAADAAAAACQAAABUaGUg" +
           "Y29tbWVudCB0byBhZGQgdG8gdGhlIGNvbmRpdGlvbi4BACgBAQAAAAEAAAAAAAAAAQH/////AAAAABVg" +
           "iQgCAAAAAAAKAAAAQWNrZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAQEBAAABAAAAFWCJ" +
           "CAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAAARhgggEAAAAAAALAAAAQWNrbm93bGVk" +
           "Z2UBAQAAAC8BAJcjAQEBAAAAAQD5CwABAPAiAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMB" +
           "AQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50" +
           "aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAA" +
           "AAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAA" +
           "AAABAf////8AAAAAFWCJCAIAAAAAAAsAAABBY3RpdmVTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAAB" +
           "ACwjAQEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAA" +
           "AAAJAAAASW5wdXROb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABMAAABTdXBwcmVz" +
           "c2VkT3JTaGVsdmVkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAsAAABOb3JtYWxTdGF0" +
           "ZQEBAAAALgBEABH/////AQH/////AAAAAARggAoBAAAAAQAYAAAATWFpbnRlbmFuY2VSZXF1aXJlZEFs" +
           "YXJtAQGOEwAjAQJ7PY4TAAD/////GwAAABVgiQgCAAAAAAAHAAAARXZlbnRJZAEBAAAALgBEAA//////" +
           "AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRUeXBlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJ" +
           "CAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABT" +
           "b3VyY2VOYW1lAQEAAAAuAEQADP////8BAf////8AAAAAFWCJCAIAAAAAAAQAAABUaW1lAQEAAAAuAEQB" +
           "ACYB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB/////wEB" +
           "/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAA" +
           "AAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf////8BAf////8AAAAAFWCJCAIAAAAAABAAAABDb25kaXRp" +
           "b25DbGFzc0lkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAABIAAABDb25kaXRpb25DbGFz" +
           "c05hbWUBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAADQAAAENvbmRpdGlvbk5hbWUBAQAA" +
           "AC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAEJyYW5jaElkAQEAAAAuAEQAEf////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "DAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAAEBAAABAAAAFWCJCAIAAAAA" +
           "AAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEBAAAALwEA" +
           "KiMAE/////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/" +
           "////AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFzdFNldmVyaXR5AQEAAAAvAQAqIwAF/////wEB////" +
           "/wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAA" +
           "FWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAqIwAV/////wEB/////wEAAAAVYIkIAgAAAAAADwAA" +
           "AFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABDbGll" +
           "bnRVc2VySWQBAQAAAC4ARAAM/////wEB/////wAAAAAEYYIIBAAAAAAABwAAAERpc2FibGUBAQAAAC8B" +
           "AEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAGAAAARW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA" +
           "+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENvbW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5CwABAA0L" +
           "AQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2" +
           "ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21t" +
           "ZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFk" +
           "ZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAAAAoAAABB" +
           "Y2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElk" +
           "AQEAAAAuAEQAAf////8BAf////8AAAAABGGCCAQAAAAAAAsAAABBY2tub3dsZWRnZQEBAAAALwEAlyMB" +
           "AQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAAB" +
           "ACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhl" +
           "IGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhl" +
           "IGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAV" +
           "YIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAV" +
           "YIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAkAAABJbnB1dE5v" +
           "ZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAAEwAAAFN1cHByZXNzZWRPclNoZWx2ZWQB" +
           "AQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAACwAAAE5vcm1hbFN0YXRlAQEAAAAuAEQAEf//" +
           "//8BAf////8AAAAA";
        #endregion
        #endif
        #endregion

        #region Public Properties
        #endregion

        #region Overridden Methods
        #endregion

        #region Private Fields
        #endregion
    }
    #endif
    #endregion
}