/* ========================================================================
 * Copyright (c) 2005-2021 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.Runtime.Serialization;
using Opc.Ua;
using Opc.Ua.DI;
using BoilerModel1;

namespace BoilerModel2
{
    #region BoilerState Class
    #if (!OPCUA_EXCLUDE_BoilerState)
    /// <remarks />
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Opc.Ua.ModelCompiler", "1.0.0.0")]
    public partial class BoilerState : DeviceTypeState
    {
        #region Constructors
        /// <remarks />
        public BoilerState(NodeState parent) : base(parent)
        {
        }

        /// <remarks />
        protected override NodeId GetDefaultTypeDefinitionId(NamespaceTable namespaceUris)
        {
            return Opc.Ua.NodeId.Create(BoilerModel2.ObjectTypes.Boiler, BoilerModel2.Namespaces.Boiler2, namespaceUris);
        }

        #if (!OPCUA_EXCLUDE_InitializationStrings)
        /// <remarks />
        protected override void Initialize(ISystemContext context)
        {
            base.Initialize(context);
            Initialize(context, InitializationString);
            InitializeOptionalChildren(context);
        }

        /// <remarks />
        protected override void Initialize(ISystemContext context, NodeState source)
        {
            InitializeOptionalChildren(context);
            base.Initialize(context, source);
        }

        /// <remarks />
        protected override void InitializeOptionalChildren(ISystemContext context)
        {
            base.InitializeOptionalChildren(context);
        }

        #region Initialization String
        private const string InitializationString =
           "AwAAACcAAABodHRwOi8vbWljcm9zb2Z0LmNvbS9PcGMvT3BjUGxjL0JvaWxlcjIfAAAAaHR0cDovL29w" +
           "Y2ZvdW5kYXRpb24ub3JnL1VBL0RJLyYAAABodHRwOi8vbWljcm9zb2Z0LmNvbS9PcGMvT3BjUGxjL0Jv" +
           "aWxlcv////8EYIACAQAAAAEADgAAAEJvaWxlckluc3RhbmNlAQHoAwEB6APoAwAA/////xIAAAAkYIAK" +
           "AQAAAAIADAAAAFBhcmFtZXRlclNldAEBlhMDAAAAABcAAABGbGF0IGxpc3Qgb2YgUGFyYW1ldGVycwAv" +
           "ADqWEwAA/////wkAAAAVYIkKAgAAAAEAFgAAAFRlbXBlcmF0dXJlQ2hhbmdlU3BlZWQBAYkXAC8AP4kX" +
           "AAAACv////8DA/////8AAAAAFWCpCgIAAAABAA8AAABCYXNlVGVtcGVyYXR1cmUBAYoXAC8AP4oXAAAK" +
           "AACgQQAK/////wMD/////wAAAAAVYIkKAgAAAAEAEQAAAFRhcmdldFRlbXBlcmF0dXJlAQGLFwAvAD+L" +
           "FwAAAAr/////AwP/////AAAAABVgqQoCAAAAAQATAAAATWFpbnRlbmFuY2VJbnRlcnZhbAEBjBcALwA/" +
           "jBcAAAY8AAAAAAb/////AwP/////AAAAABVgiQoCAAAAAQAeAAAAT3ZlcmhlYXRlZFRocmVzaG9sZFRl" +
           "bXBlcmF0dXJlAQGNFwAvAD+NFwAAAAr/////AwP/////AAAAABVgiQoCAAAAAQALAAAASGVhdGVyU3Rh" +
           "dGUBAY4XAC8AP44XAAAAAf////8DA/////8AAAAAFWCpCgIAAAABABIAAABDdXJyZW50VGVtcGVyYXR1" +
           "cmUBAY8XAC8AP48XAAAKAACgQQAK/////wEB/////wAAAAAVYIkKAgAAAAEACAAAAFByZXNzdXJlAQGQ" +
           "FwAvAD+QFwAAAAr/////AQH/////AAAAABVgiQoCAAAAAQAKAAAAT3ZlcmhlYXRlZAEBkRcALwA/kRcA" +
           "AAAB/////wEB/////wAAAAAkYIAKAQAAAAIACQAAAE1ldGhvZFNldAEBlRMDAAAAABQAAABGbGF0IGxp" +
           "c3Qgb2YgTWV0aG9kcwAvADqVEwAA/////wEAAAAEYYIKBAAAAAEABgAAAFN3aXRjaAEBWBsALwEBWBtY" +
           "GwAAAQH/////AgAAADdgqQoCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAYcXAwAAAABAAAAAdGhlIGRl" +
           "ZmluaXRpb24gb2YgdGhlIGlucHV0IGFyZ3VtZW50IG9mIG1ldGhvZCAyOkJvaWxlci4yOlN3aXRjaAAu" +
           "AESHFwAAlgEAAAABACoBAREAAAACAAAAT24AAf////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8A" +
           "AAAAN2CJCgIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBAYgXAwAAAABCAAAAdGhlIGRlZmluaXRpb24g" +
           "b2YgdGhlIG91dHB1dCBhcmd1bWVudHMgb2YgbWV0aG9kIDI6Qm9pbGVyLjI6U3dpdGNoAC4ARIgXAAAB" +
           "ACgBAQAAAAEAAAAAAAAAAQH/////AAAAADVgiQoCAAAAAgAMAAAATWFudWZhY3R1cmVyAQF7FwMAAAAA" +
           "MAAAAE5hbWUgb2YgdGhlIGNvbXBhbnkgdGhhdCBtYW51ZmFjdHVyZWQgdGhlIGRldmljZQAuAER7FwAA" +
           "ABX/////AQH/////AAAAABVgiQoCAAAAAgAPAAAATWFudWZhY3R1cmVyVXJpAQF8FwAuAER8FwAAAAz/" +
           "////AQH/////AAAAADVgiQoCAAAAAgAFAAAATW9kZWwBAX0XAwAAAAAYAAAATW9kZWwgbmFtZSBvZiB0" +
           "aGUgZGV2aWNlAC4ARH0XAAAAFf////8BAf////8AAAAANWCJCgIAAAACABAAAABIYXJkd2FyZVJldmlz" +
           "aW9uAQF/FwMAAAAALAAAAFJldmlzaW9uIGxldmVsIG9mIHRoZSBoYXJkd2FyZSBvZiB0aGUgZGV2aWNl" +
           "AC4ARH8XAAAADP////8BAf////8AAAAANWCJCgIAAAACABAAAABTb2Z0d2FyZVJldmlzaW9uAQGAFwMA" +
           "AAAANQAAAFJldmlzaW9uIGxldmVsIG9mIHRoZSBzb2Z0d2FyZS9maXJtd2FyZSBvZiB0aGUgZGV2aWNl" +
           "AC4ARIAXAAAADP////8BAf////8AAAAANWCJCgIAAAACAA4AAABEZXZpY2VSZXZpc2lvbgEBgRcDAAAA" +
           "ACQAAABPdmVyYWxsIHJldmlzaW9uIGxldmVsIG9mIHRoZSBkZXZpY2UALgBEgRcAAAAM/////wEB////" +
           "/wAAAAAVYIkKAgAAAAIACwAAAFByb2R1Y3RDb2RlAQF+FwAuAER+FwAAAAz/////AQH/////AAAAADVg" +
           "iQoCAAAAAgAMAAAARGV2aWNlTWFudWFsAQGCFwMAAAAAWgAAAEFkZHJlc3MgKHBhdGhuYW1lIGluIHRo" +
           "ZSBmaWxlIHN5c3RlbSBvciBhIFVSTCB8IFdlYiBhZGRyZXNzKSBvZiB1c2VyIG1hbnVhbCBmb3IgdGhl" +
           "IGRldmljZQAuAESCFwAAAAz/////AQH/////AAAAABVgiQoCAAAAAgALAAAARGV2aWNlQ2xhc3MBAYMX" +
           "AC4ARIMXAAAADP////8BAf////8AAAAANWCJCgIAAAACAAwAAABTZXJpYWxOdW1iZXIBAYQXAwAAAABN" +
           "AAAASWRlbnRpZmllciB0aGF0IHVuaXF1ZWx5IGlkZW50aWZpZXMsIHdpdGhpbiBhIG1hbnVmYWN0dXJl" +
           "ciwgYSBkZXZpY2UgaW5zdGFuY2UALgBEhBcAAAAM/////wEB/////wAAAAAVYIkKAgAAAAIAEgAAAFBy" +
           "b2R1Y3RJbnN0YW5jZVVyaQEBhRcALgBEhRcAAAAM/////wEB/////wAAAAA1YIkKAgAAAAIADwAAAFJl" +
           "dmlzaW9uQ291bnRlcgEBhhcDAAAAAGkAAABBbiBpbmNyZW1lbnRhbCBjb3VudGVyIGluZGljYXRpbmcg" +
           "dGhlIG51bWJlciBvZiB0aW1lcyB0aGUgc3RhdGljIGRhdGEgd2l0aGluIHRoZSBEZXZpY2UgaGFzIGJl" +
           "ZW4gbW9kaWZpZWQALgBEhhcAAAAG/////wEB/////wAAAAAVYIkKAgAAAAIABwAAAEFzc2V0SWQBAXgX" +
           "AC4ARHgXAAAADP////8BAf////8AAAAAFWCJCgIAAAACAA0AAABDb21wb25lbnROYW1lAQF5FwAuAER5" +
           "FwAAABX/////AQH/////AAAAABVgiQoCAAAAAgAMAAAARGV2aWNlSGVhbHRoAQF6FwAvAD96FwAAAQJk" +
           "GP////8BAf////8AAAAABGCACgEAAAACABIAAABEZXZpY2VIZWFsdGhBbGFybXMBAYoTAC8APYoTAAD/" +
           "////BAAAAARggAoBAAAAAQAMAAAARmFpbHVyZUFsYXJtAQGLEwAjAQK8O4sTAAD/////GwAAABVgiQgC" +
           "AAAAAAAHAAAARXZlbnRJZAEBAAAALgBEAA//////AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZlbnRU" +
           "eXBlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAuAEQA" +
           "Ef////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOYW1lAQEAAAAuAEQADP////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAQAAABUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAACwAA" +
           "AFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3NhZ2UB" +
           "AQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAABAAAABDb25kaXRpb25DbGFzc0lkAQEAAAAuAEQAEf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAABIAAABDb25kaXRpb25DbGFzc05hbWUBAQAAAC4ARAAV/////wEB/////wAAAAAV" +
           "YIkIAgAAAAAADQAAAENvbmRpdGlvbk5hbWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "CAAAAEJyYW5jaElkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4BAQAA" +
           "AC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMAFf//" +
           "//8BAQEAAAABACwjAAEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////AAAA" +
           "ABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEBAAAALwEAKiMAE/////8BAf////8BAAAAFWCJCAIAAAAAAA8A" +
           "AABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAATGFz" +
           "dFNldmVyaXR5AQEAAAAvAQAqIwAF/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVz" +
           "dGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAvAQAq" +
           "IwAV/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAmAf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAAAwAAABDbGllbnRVc2VySWQBAQAAAC4ARAAM/////wEB/////wAA" +
           "AAAEYYIIBAAAAAAABwAAAERpc2FibGUBAQAAAC8BAEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAA" +
           "AAAGAAAARW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFkZENv" +
           "bW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5CwABAA0LAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVu" +
           "dHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlk" +
           "ZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////" +
           "AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAA" +
           "AAAAAAABAf////8AAAAAFWCJCAIAAAAAAAoAAABBY2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAA" +
           "AAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAABGGCCAQA" +
           "AAAAAAsAAABBY2tub3dsZWRnZQEBAAAALwEAlyMBAQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAAAA4A" +
           "AABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAAAAAD" +
           "AAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAA" +
           "AENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRp" +
           "b24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEAAAAv" +
           "AQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAAAkAAABJbnB1dE5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAAEwAAAFN1cHByZXNzZWRPclNoZWx2ZWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAA" +
           "AAAACwAAAE5vcm1hbFN0YXRlAQEAAAAuAEQAEf////8BAf////8AAAAABGCACgEAAAABABIAAABDaGVj" +
           "a0Z1bmN0aW9uQWxhcm0BAYwTACMBAlE8jBMAAP////8bAAAAFWCJCAIAAAAAAAcAAABFdmVudElkAQEA" +
           "AAAuAEQAD/////8BAf////8AAAAAFWCJCAIAAAAAAAkAAABFdmVudFR5cGUBAQAAAC4ARAAR/////wEB" +
           "/////wAAAAAVYIkIAgAAAAAACgAAAFNvdXJjZU5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAACgAAAFNvdXJjZU5hbWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAAAAAABAAAAFRp" +
           "bWUBAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAALAAAAUmVjZWl2ZVRpbWUBAQAAAC4A" +
           "RAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAATWVzc2FnZQEBAAAALgBEABX/////AQH/////" +
           "AAAAABVgiQgCAAAAAAAIAAAAU2V2ZXJpdHkBAQAAAC4ARAAF/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "EAAAAENvbmRpdGlvbkNsYXNzSWQBAQAAAC4ARAAR/////wEB/////wAAAAAVYIkIAgAAAAAAEgAAAENv" +
           "bmRpdGlvbkNsYXNzTmFtZQEBAAAALgBEABX/////AQH/////AAAAABVgiQgCAAAAAAANAAAAQ29uZGl0" +
           "aW9uTmFtZQEBAAAALgBEAAz/////AQH/////AAAAABVgiQgCAAAAAAAIAAAAQnJhbmNoSWQBAQAAAC4A" +
           "RAAR/////wEB/////wAAAAAVYIkIAgAAAAAABgAAAFJldGFpbgEBAAAALgBEAAH/////AQH/////AAAA" +
           "ABVgiQgCAAAAAAAMAAAARW5hYmxlZFN0YXRlAQEAAAAvAQAjIwAV/////wEBAQAAAAEALCMAAQEAAAEA" +
           "AAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAcAAABRdWFs" +
           "aXR5AQEAAAAvAQAqIwAT/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEB" +
           "AAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABMYXN0U2V2ZXJpdHkBAQAAAC8BACoj" +
           "AAX/////AQH/////AQAAABVgiQgCAAAAAAAPAAAAU291cmNlVGltZXN0YW1wAQEAAAAuAEQBACYB////" +
           "/wEB/////wAAAAAVYIkIAgAAAAAABwAAAENvbW1lbnQBAQAAAC8BACojABX/////AQH/////AQAAABVg" +
           "iQgCAAAAAAAPAAAAU291cmNlVGltZXN0YW1wAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAA" +
           "AAAADAAAAENsaWVudFVzZXJJZAEBAAAALgBEAAz/////AQH/////AAAAAARhgggEAAAAAAAHAAAARGlz" +
           "YWJsZQEBAAAALwEARCMBAQEAAAABAPkLAAEA8woAAAAABGGCCAQAAAAAAAYAAABFbmFibGUBAQAAAC8B" +
           "AEMjAQEBAAAAAQD5CwABAPMKAAAAAARhgggEAAAAAAAKAAAAQWRkQ29tbWVudAEBAAAALwEARSMBAQEA" +
           "AAABAPkLAAEADQsBAAAAF2CpCAIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoB" +
           "AUYAAAAHAAAARXZlbnRJZAAP/////wAAAAADAAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2" +
           "ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAABwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNv" +
           "bW1lbnQgdG8gYWRkIHRvIHRoZSBjb25kaXRpb24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkI" +
           "AgAAAAAACgAAAEFja2VkU3RhdGUBAQAAAC8BACMjABX/////AQEBAAAAAQAsIwEBAQAAAQAAABVgiQgC" +
           "AAAAAAACAAAASWQBAQAAAC4ARAAB/////wEB/////wAAAAAEYYIIBAAAAAAACwAAAEFja25vd2xlZGdl" +
           "AQEAAAAvAQCXIwEBAQAAAAEA+QsAAQDwIgEAAAAXYKkIAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQEA" +
           "AAAuAESWAgAAAAEAKgEBRgAAAAcAAABFdmVudElkAA//////AAAAAAMAAAAAKAAAAFRoZSBpZGVudGlm" +
           "aWVyIGZvciB0aGUgZXZlbnQgdG8gY29tbWVudC4BACoBAUIAAAAHAAAAQ29tbWVudAAV/////wAAAAAD" +
           "AAAAACQAAABUaGUgY29tbWVudCB0byBhZGQgdG8gdGhlIGNvbmRpdGlvbi4BACgBAQAAAAEAAAAAAAAA" +
           "AQH/////AAAAABVgiQgCAAAAAAALAAAAQWN0aXZlU3RhdGUBAQAAAC8BACMjABX/////AQEBAAAAAQAs" +
           "IwEBAQAAAQAAABVgiQgCAAAAAAACAAAASWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "CQAAAElucHV0Tm9kZQEBAAAALgBEABH/////AQH/////AAAAABVgiQgCAAAAAAATAAAAU3VwcHJlc3Nl" +
           "ZE9yU2hlbHZlZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAALAAAATm9ybWFsU3RhdGUB" +
           "AQAAAC4ARAAR/////wEB/////wAAAAAEYIAKAQAAAAEADAAAAE9mZlNwZWNBbGFybQEBjRMAIwEC5jyN" +
           "EwAA/////xsAAAAVYIkIAgAAAAAABwAAAEV2ZW50SWQBAQAAAC4ARAAP/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAACQAAAEV2ZW50VHlwZQEBAAAALgBEABH/////AQH/////AAAAABVgiQgCAAAAAAAKAAAAU291" +
           "cmNlTm9kZQEBAAAALgBEABH/////AQH/////AAAAABVgiQgCAAAAAAAKAAAAU291cmNlTmFtZQEBAAAA" +
           "LgBEAAz/////AQH/////AAAAABVgiQgCAAAAAAAEAAAAVGltZQEBAAAALgBEAQAmAf////8BAf////8A" +
           "AAAAFWCJCAIAAAAAAAsAAABSZWNlaXZlVGltZQEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIA" +
           "AAAAAAcAAABNZXNzYWdlAQEAAAAuAEQAFf////8BAf////8AAAAAFWCJCAIAAAAAAAgAAABTZXZlcml0" +
           "eQEBAAAALgBEAAX/////AQH/////AAAAABVgiQgCAAAAAAAQAAAAQ29uZGl0aW9uQ2xhc3NJZAEBAAAA" +
           "LgBEABH/////AQH/////AAAAABVgiQgCAAAAAAASAAAAQ29uZGl0aW9uQ2xhc3NOYW1lAQEAAAAuAEQA" +
           "Ff////8BAf////8AAAAAFWCJCAIAAAAAAA0AAABDb25kaXRpb25OYW1lAQEAAAAuAEQADP////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAgAAABCcmFuY2hJZAEBAAAALgBEABH/////AQH/////AAAAABVgiQgCAAAA" +
           "AAAGAAAAUmV0YWluAQEAAAAuAEQAAf////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABFbmFibGVkU3Rh" +
           "dGUBAQAAAC8BACMjABX/////AQEBAAAAAQAsIwABAQAAAQAAABVgiQgCAAAAAAACAAAASWQBAQAAAC4A" +
           "RAAB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAFF1YWxpdHkBAQAAAC8BACojABP/////AQH/////" +
           "AQAAABVgiQgCAAAAAAAPAAAAU291cmNlVGltZXN0YW1wAQEAAAAuAEQBACYB/////wEB/////wAAAAAV" +
           "YIkIAgAAAAAADAAAAExhc3RTZXZlcml0eQEBAAAALwEAKiMABf////8BAf////8BAAAAFWCJCAIAAAAA" +
           "AA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAHAAAA" +
           "Q29tbWVudAEBAAAALwEAKiMAFf////8BAf////8BAAAAFWCJCAIAAAAAAA8AAABTb3VyY2VUaW1lc3Rh" +
           "bXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAAQ2xpZW50VXNlcklkAQEAAAAu" +
           "AEQADP////8BAf////8AAAAABGGCCAQAAAAAAAcAAABEaXNhYmxlAQEAAAAvAQBEIwEBAQAAAAEA+QsA" +
           "AQDzCgAAAAAEYYIIBAAAAAAABgAAAEVuYWJsZQEBAAAALwEAQyMBAQEAAAABAPkLAAEA8woAAAAABGGC" +
           "CAQAAAAAAAoAAABBZGRDb21tZW50AQEAAAAvAQBFIwEBAQAAAAEA+QsAAQANCwEAAAAXYKkIAgAAAAAA" +
           "DgAAAElucHV0QXJndW1lbnRzAQEAAAAuAESWAgAAAAEAKgEBRgAAAAcAAABFdmVudElkAA//////AAAA" +
           "AAMAAAAAKAAAAFRoZSBpZGVudGlmaWVyIGZvciB0aGUgZXZlbnQgdG8gY29tbWVudC4BACoBAUIAAAAH" +
           "AAAAQ29tbWVudAAV/////wAAAAADAAAAACQAAABUaGUgY29tbWVudCB0byBhZGQgdG8gdGhlIGNvbmRp" +
           "dGlvbi4BACgBAQAAAAEAAAAAAAAAAQH/////AAAAABVgiQgCAAAAAAAKAAAAQWNrZWRTdGF0ZQEBAAAA" +
           "LwEAIyMAFf////8BAQEAAAABACwjAQEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////" +
           "AQH/////AAAAAARhgggEAAAAAAALAAAAQWNrbm93bGVkZ2UBAQAAAC8BAJcjAQEBAAAAAQD5CwABAPAi" +
           "AQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2" +
           "ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhlIGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21t" +
           "ZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFk" +
           "ZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAAAQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAAAAsAAABB" +
           "Y3RpdmVTdGF0ZQEBAAAALwEAIyMAFf////8BAQEAAAABACwjAQEBAAABAAAAFWCJCAIAAAAAAAIAAABJ" +
           "ZAEBAAAALgBEAAH/////AQH/////AAAAABVgiQgCAAAAAAAJAAAASW5wdXROb2RlAQEAAAAuAEQAEf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAABMAAABTdXBwcmVzc2VkT3JTaGVsdmVkAQEAAAAuAEQAAf////8B" +
           "Af////8AAAAAFWCJCAIAAAAAAAsAAABOb3JtYWxTdGF0ZQEBAAAALgBEABH/////AQH/////AAAAAARg" +
           "gAoBAAAAAQAYAAAATWFpbnRlbmFuY2VSZXF1aXJlZEFsYXJtAQGOEwAjAQJ7PY4TAAD/////GwAAABVg" +
           "iQgCAAAAAAAHAAAARXZlbnRJZAEBAAAALgBEAA//////AQH/////AAAAABVgiQgCAAAAAAAJAAAARXZl" +
           "bnRUeXBlAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOb2RlAQEAAAAu" +
           "AEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAoAAABTb3VyY2VOYW1lAQEAAAAuAEQADP////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAAAQAAABUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAA" +
           "CwAAAFJlY2VpdmVUaW1lAQEAAAAuAEQBACYB/////wEB/////wAAAAAVYIkIAgAAAAAABwAAAE1lc3Nh" +
           "Z2UBAQAAAC4ARAAV/////wEB/////wAAAAAVYIkIAgAAAAAACAAAAFNldmVyaXR5AQEAAAAuAEQABf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAABAAAABDb25kaXRpb25DbGFzc0lkAQEAAAAuAEQAEf////8BAf//" +
           "//8AAAAAFWCJCAIAAAAAABIAAABDb25kaXRpb25DbGFzc05hbWUBAQAAAC4ARAAV/////wEB/////wAA" +
           "AAAVYIkIAgAAAAAADQAAAENvbmRpdGlvbk5hbWUBAQAAAC4ARAAM/////wEB/////wAAAAAVYIkIAgAA" +
           "AAAACAAAAEJyYW5jaElkAQEAAAAuAEQAEf////8BAf////8AAAAAFWCJCAIAAAAAAAYAAABSZXRhaW4B" +
           "AQAAAC4ARAAB/////wEB/////wAAAAAVYIkIAgAAAAAADAAAAEVuYWJsZWRTdGF0ZQEBAAAALwEAIyMA" +
           "Ff////8BAQEAAAABACwjAAEBAAABAAAAFWCJCAIAAAAAAAIAAABJZAEBAAAALgBEAAH/////AQH/////" +
           "AAAAABVgiQgCAAAAAAAHAAAAUXVhbGl0eQEBAAAALwEAKiMAE/////8BAf////8BAAAAFWCJCAIAAAAA" +
           "AA8AAABTb3VyY2VUaW1lc3RhbXABAQAAAC4ARAEAJgH/////AQH/////AAAAABVgiQgCAAAAAAAMAAAA" +
           "TGFzdFNldmVyaXR5AQEAAAAvAQAqIwAF/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRp" +
           "bWVzdGFtcAEBAAAALgBEAQAmAf////8BAf////8AAAAAFWCJCAIAAAAAAAcAAABDb21tZW50AQEAAAAv" +
           "AQAqIwAV/////wEB/////wEAAAAVYIkIAgAAAAAADwAAAFNvdXJjZVRpbWVzdGFtcAEBAAAALgBEAQAm" +
           "Af////8BAf////8AAAAAFWCJCAIAAAAAAAwAAABDbGllbnRVc2VySWQBAQAAAC4ARAAM/////wEB////" +
           "/wAAAAAEYYIIBAAAAAAABwAAAERpc2FibGUBAQAAAC8BAEQjAQEBAAAAAQD5CwABAPMKAAAAAARhgggE" +
           "AAAAAAAGAAAARW5hYmxlAQEAAAAvAQBDIwEBAQAAAAEA+QsAAQDzCgAAAAAEYYIIBAAAAAAACgAAAEFk" +
           "ZENvbW1lbnQBAQAAAC8BAEUjAQEBAAAAAQD5CwABAA0LAQAAABdgqQgCAAAAAAAOAAAASW5wdXRBcmd1" +
           "bWVudHMBAQAAAC4ARJYCAAAAAQAqAQFGAAAABwAAAEV2ZW50SWQAD/////8AAAAAAwAAAAAoAAAAVGhl" +
           "IGlkZW50aWZpZXIgZm9yIHRoZSBldmVudCB0byBjb21tZW50LgEAKgEBQgAAAAcAAABDb21tZW50ABX/" +
           "////AAAAAAMAAAAAJAAAAFRoZSBjb21tZW50IHRvIGFkZCB0byB0aGUgY29uZGl0aW9uLgEAKAEBAAAA" +
           "AQAAAAAAAAABAf////8AAAAAFWCJCAIAAAAAAAoAAABBY2tlZFN0YXRlAQEAAAAvAQAjIwAV/////wEB" +
           "AQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf////8BAf////8AAAAABGGC" +
           "CAQAAAAAAAsAAABBY2tub3dsZWRnZQEBAAAALwEAlyMBAQEAAAABAPkLAAEA8CIBAAAAF2CpCAIAAAAA" +
           "AA4AAABJbnB1dEFyZ3VtZW50cwEBAAAALgBElgIAAAABACoBAUYAAAAHAAAARXZlbnRJZAAP/////wAA" +
           "AAADAAAAACgAAABUaGUgaWRlbnRpZmllciBmb3IgdGhlIGV2ZW50IHRvIGNvbW1lbnQuAQAqAQFCAAAA" +
           "BwAAAENvbW1lbnQAFf////8AAAAAAwAAAAAkAAAAVGhlIGNvbW1lbnQgdG8gYWRkIHRvIHRoZSBjb25k" +
           "aXRpb24uAQAoAQEAAAABAAAAAAAAAAEB/////wAAAAAVYIkIAgAAAAAACwAAAEFjdGl2ZVN0YXRlAQEA" +
           "AAAvAQAjIwAV/////wEBAQAAAAEALCMBAQEAAAEAAAAVYIkIAgAAAAAAAgAAAElkAQEAAAAuAEQAAf//" +
           "//8BAf////8AAAAAFWCJCAIAAAAAAAkAAABJbnB1dE5vZGUBAQAAAC4ARAAR/////wEB/////wAAAAAV" +
           "YIkIAgAAAAAAEwAAAFN1cHByZXNzZWRPclNoZWx2ZWQBAQAAAC4ARAAB/////wEB/////wAAAAAVYIkI" +
           "AgAAAAAACwAAAE5vcm1hbFN0YXRlAQEAAAAuAEQAEf////8BAf////8AAAAA";
        #endregion
        #endif
        #endregion

        #region Public Properties
        #endregion

        #region Overridden Methods
        #endregion

        #region Private Fields
        #endregion
    }
    #endif
    #endregion
}