<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>OpcPlc.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <LangVersion>Preview</LangVersion>
    <UseOpcUaModelSourceGenerator>true</UseOpcUaModelSourceGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration$(OpcUaPackageSuffix)" NoWarn="NU5104" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server$(OpcUaPackageSuffix)" NoWarn="NU5104" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client$(OpcUaPackageSuffix)" NoWarn="NU5104" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Gds.Client$(OpcUaPackageSuffix)" NoWarn="NU5104" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DeterministicAlarmsTests\dalm002.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PlcSimulatorFixture.Config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DeterministicAlarmsTests\dalm001.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\opc-plc.csproj" />
    <AdditionalFiles Include="..\src\Boilers\Boiler2\BoilerModel2.NodeSet2.xml"
                     ModelSourceGeneratorModelUri="http://microsoft.com/Opc/OpcPlc/Boiler"
                     ModelSourceGeneratorName="BoilerModel2" ModelSourceGeneratorPrefix="BoilerModel2" />
    <AdditionalFiles Include="..\src\CompanionSpecs\DI\Opc.Ua.DI.NodeSet2.xml"
                     ModelSourceGeneratorModelUri="http://opcfoundation.org/UA/DI/"
                     ModelSourceGeneratorName="DI" ModelSourceGeneratorPrefix="Opc.Ua.DI" />
    <AdditionalFiles Include="..\src\CompanionSpecs\WotCon\Opc.Ua.WotCon.NodeSet2.xml"
                     ModelSourceGeneratorModelUri="http://opcfoundation.org/UA/WoT-Con/"
                     ModelSourceGeneratorName="WotCon" ModelSourceGeneratorPrefix="Opc.Ua.WotCon" />
    <AdditionalFiles Include="..\src\SimpleEvent\SimpleEvents.NodeSet2.xml"
                     ModelSourceGeneratorModelUri="http://microsoft.com/Opc/OpcPlc/SimpleEvents"
                     ModelSourceGeneratorName="SimpleEvents" ModelSourceGeneratorPrefix="SimpleEvents" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestResults/**/*.cs" />
    <EmbeddedResource Remove="TestResults/**/*" />
    <None Remove="TestResults/**/*" />
    <Using Include="System.Collections.Generic" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="README.md" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ModelBaselines\GeneratedApiDifferences.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\src\Boilers\**\*.Classes.cs;..\src\CompanionSpecs\DI\*.Classes.cs;..\src\CompanionSpecs\WotCon\*.Classes.cs;..\src\SimpleEvent\*.Classes.cs"
          Link="ModelBaselines\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\src\Boilers\**\*.NodeIds.csv;..\src\Boilers\**\*.NodeSet2.xml;..\src\CompanionSpecs\DI\*.NodeIds.csv;..\src\CompanionSpecs\DI\*.NodeSet2.xml;..\src\CompanionSpecs\WotCon\*.NodeIds.csv;..\src\CompanionSpecs\WotCon\*.NodeSet2.xml;..\src\SimpleEvent\*.NodeIds.csv;..\src\SimpleEvent\*.NodeSet2.xml"
          Link="ModelBaselines\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
