#
# Build images in acr
#
jobs:
- job: imagesprep
  displayName: Prepare Image Jobs
  pool:
    name: Hosted Windows 2019 with VS2019
  variables:
    skipComponentGovernanceDetection: true
  steps:
#  - task: AzureCLI@1
  - task: PowerShell@2
    name: acrmatrix
    displayName: Prepare Builds
    inputs: 
      targetType: filePath
      filePath: ./tools/scripts/acr-matrix.ps1
#      azureSubscription: ${{coalesce(variables.AZURE_SUBSCRIPTION, 'azureiiot')}}
#      scriptLocation: inlineScript
#      inlineScript: powershell ./tools/scripts/acr-matrix.ps1 -Registry=${{coalesce(variables.BUILD_REGISTRY, 'johanngdevacr')}} -Subscription=${{coalesce(variables.AZURE_SUBSCRIPTION, 'IOT-OPC-WALLS')}} -Build
      arguments: -Registry "$[variables.BUILD_REGISTRY]" -Subscription "$[variables.AZURE_SUBSCRIPTION]"
- job: imagesall
  displayName: Build Images for
  pool:
    name: Hosted Windows 2019 with VS2019
  dependsOn: imagesprep
  strategy:
    matrix: $[ dependencies.imagesprep.outputs['acrmatrix.acrMatrix'] ]
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 3.1.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
#  - task: AzureCLI@1
  - task: PowerShell@2
    name: acrbuildr
    displayName: Build Release Images
    inputs:
#      azureSubscription: ${{coalesce(variables.AZURE_SUBSCRIPTION, 'azureiiot')}}
      targetType: filePath
      filePath: ./tools/scripts/acr-build.ps1
#      scriptLocation: inlineScript
#      inlineScript: powershell ./tools/scripts/acr-build.ps1 $(dockerFolder) -Registry=${{coalesce(variables.BUILD_REGISTRY, 'johanngdevacr')}} -Subscription=${{coalesce(variables.AZURE_SUBSCRIPTION, 'IOT-OPC-WALLS')}}
      arguments: $(dockerFolder) -Registry=$(BUILD_REGISTRY) -Subscription=$(AZURE_SUBSCRIPTION)
#  - task: AzureCLI@1
  - task: PowerShell@2
    name: acrbuildd
    displayName: Build Debug Images
    inputs:
#      azureSubscription: ${{coalesce(variables.AZURE_SUBSCRIPTION, 'azureiiot')}}
      targetType: filePath
      filePath: ./tools/scripts/acr-build.ps1
#      scriptLocation: inlineScript
#      inlineScript: powershell ./tools/scripts/acr-build.ps1 $(dockerFolder) -Registry=$env:BUILD_REGISTRY -Subscription=$env:AZURE_SUBSCRIPTION -debug
#      inlineScript: powershell ./tools/scripts/acr-build.ps1 $(dockerFolder) -Registry=${{coalesce(variables.BUILD_REGISTRY, 'johanngdevacr')}} -Subscription=${{coalesce(variables.AZURE_SUBSCRIPTION, 'IOT-OPC-WALLS')}} -debug
      arguments: $(dockerFolder) -Registry=$(BUILD_REGISTRY) -Subscription=$(AZURE_SUBSCRIPTION) -debug
