<Project>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)/../contentFiles/**/*.*"
          Link="%(RecursiveDir)%(Filename)%(Extension)"
          TargetPath="%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest"
          Pack="false" />
  </ItemGroup>
</Project>
